### ISSUE TITLE
Emulator timeout inside gitlab-ci runer

### ISSUE THREAD

**Issue by jcarlosgalvezm** [fwojciec/dsemu#1]
Hi, 

When I try to run dsemu inside a gitlab-ci runner I get the following error:

```
 ______________________ ERROR at setup of test_map_picker _______________________
    @pytest.fixture(scope="session")
    def emulator():
>       with Emulator() as emulator:
tests/conftest.py:18: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/root/venv/lib/python3.8/site-packages/dsemu/__init__.py:57: in __enter__
    self.start()
/root/venv/lib/python3.8/site-packages/dsemu/__init__.py:74: in start
    self._start()
/root/venv/lib/python3.8/site-packages/dsemu/__init__.py:126: in _start
    self._confirm_startup()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <dsemu.Emulator object at 0x7f3ac375cc10>
    def _confirm_startup(self) -> None:
        t = time.time()
        while True:
            if self._is_healthy():
                return
            if time.time() - t >= self._timeout:
>               raise EmulatorException("confirm startup timed out")
E               dsemu.EmulatorException: confirm startup timed out
/root/venv/lib/python3.8/site-packages/dsemu/__init__.py:158: EmulatorException
```
But if I try to run the tests locally it runs well.
Any ideas on what may be happening?

gcloud and cloud-datastore-emulator component are also installed into the gitlab-ci
 
Cheers and thanks in advance

**Comment by fwojciec** [comment]
Looks like it times out on init -- I guess I should provide a more helpful error message in either case...
I'll have a look over the weekend to see if I can reproduce and hopefully fix.  I haven't actually tried running the Python version of this library in CI/CD but I we do have a [Go version](https://github.com/fwojciec/datastore-emulator-go) running in ci/cd pipelines in production code without any issues, so it should be possible to solve.

One thing I remember from getting the emulator to run in our CI/CD was that I also had to install the gcloud tool "beta" package (I don't remember the exact name unfortunately) in addition to the emulator package...

**Comment by jcarlosgalvezm** [comment]
If it helps you this is what my .gitlab-ci.yml file looks like, as you can see beta component is also installed:

```
# https://hub.docker.com/r/library/python/tags/
image: python:3.8

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - ${HOME}/.cache/pip
    - ${HOME}/venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv ${HOME}/venv
  - source ${HOME}/venv/bin/activate
  # Install CA certs, openssl to https downloads, python for gcloud sdk
  - apt-get install make ca-certificates openssl python
  - update-ca-certificates

  # Download and install Google Cloud SDK
  - curl https://sdk.cloud.google.com > install.sh
  - bash install.sh --disable-prompts --install-dir=${HOME}
  - PATH=${HOME}/google-cloud-sdk/bin:${PATH}
  - gcloud --quiet components update
  - gcloud components install cloud-datastore-emulator
  - gcloud components install beta
  - gcloud components install appctl
  - gcloud components install cloud-build-local 
  - gcloud components install app-engine-python
  - gcloud components install app-engine-python-extras
  - FLASK_ENV=testing

test:
  script:
    - pip install -r requirements-test.txt
    - pytest --cov .
```
